### ISSUE TITLE
 Error: Cannot find module '../config/msfrpc-client.json'

### ISSUE THREAD

**Issue by MavericksGooses** [Mister2Tone/metasploit-webapp#31]
I am trying to run "node ./bin/www" but receive the following error

─(root㉿kali)-[/home/kali/metasploit-webapp/bin]
└─# node www                                
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '../config/msfrpc-client.json'
Require stack:
- /home/kali/metasploit-webapp/lib/msfrpc-connection.js
- /home/kali/metasploit-webapp/app.js
- /home/kali/metasploit-webapp/bin/www
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)                                                                           
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/kali/metasploit-webapp/lib/msfrpc-connection.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/kali/metasploit-webapp/app.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/kali/metasploit-webapp/bin/www:7:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/kali/metasploit-webapp/lib/msfrpc-connection.js',
    '/home/kali/metasploit-webapp/app.js',
    '/home/kali/metasploit-webapp/bin/www'
  ]
}

**Comment by Izzy-Graydust** [comment]
node ./bin/www
node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module './config/msfrpc-client.json'
Require stack:
- /home/zxwar1111/Desktop/metasploit-webapp/lib/msfrpc-connection.js
- /home/zxwar1111/Desktop/metasploit-webapp/app.js
- /home/zxwar1111/Desktop/metasploit-webapp/bin/www
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)                                                               
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/zxwar1111/Desktop/metasploit-webapp/lib/msfrpc-connection.js:3:22)                                     
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)                                                                
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/zxwar1111/Desktop/metasploit-webapp/app.js:7:14)                                                       
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)                                                                
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/zxwar1111/Desktop/metasploit-webapp/bin/www:7:11)                                                      
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)                                                                
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/zxwar1111/Desktop/metasploit-webapp/lib/msfrpc-connection.js',                                                               
    '/home/zxwar1111/Desktop/metasploit-webapp/app.js',
    '/home/zxwar1111/Desktop/metasploit-webapp/bin/www'
  ]
}

Node.js v18.13.0
